config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :schedulings
    resources :orders
    resources :campaigns
    resources :discounts
    resources :services
    resources :products
    resources :suppliers
    resources :clients
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include Fae::BaseModelConcern

  has_many :campaign_clients
  has_many :clients, through: :campaign_clients

  validates :title, presence: true
  validates :body, presence: true

  after_save :schedule_emails

  def fae_display_field
    title
  end

  def schedule_emails
    Client.all.each do |client|
      CampaignClient.create(campaign: self, client: client)
      CampaingJob.perform_later(client, title, body)
    end
  end
end

app/models/campaign_client.rb
class CampaignClient < ApplicationRecord
  belongs_to :campaign
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
  include Fae::BaseModelConcern

  has_many :campaign_clients
  has_many :campaigns, through: :campaign_clients, dependent: :destroy
  has_many :addresses, as: :addressable

  accepts_nested_attributes_for :addresses, allow_destroy: true

  validates :phone, presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: Fae.validation_helpers.email_regex,
              message: 'A valid email format is required'
            }

  def fae_display_field
    name
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  include Fae::BaseModelConcern

  enum kind: [:money, :percentual]

  validates :title, presence: true, uniqueness: true
  validates :value, presence: true
  validates :kind, presence: true

  def fae_display_field
    title
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include Fae::BaseModelConcern
  enum status: { finished: 0, canceled: 1 }

  belongs_to :discount
  belongs_to :client

  has_many :order_products
  has_many :products, through: :order_products, dependent: :destroy

  has_many :order_services
  has_many :services, through: :order_services, dependent: :destroy

  validates :client, presence: true

  before_save :set_total

  def fae_display_field
    id
  end

  def self.for_fae_index
    order(:id)
  end

  private

  def set_total
    self.total = products.map(&:price).inject(0, :+)
    self.total += services.map(&:price).inject(0, :+)

    apply_discount_to_total
  end

  def apply_discount_to_total
    if discount.present?
      if discount.money?
        apply_money_discount
      else
        apply_percentual_discount
      end
    end
  end

  def apply_money_discount
    if discount.value > self.total
      self.total = 0
    else
      self.total -= discount.value
    end
  end

  def apply_percentual_discount
    convert_to_money = self.total * (discount.value / 100)
    self.total = self.total - convert_to_money
    self.total = 0 if self.total < 0
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_service.rb
class OrderService < ApplicationRecord
  belongs_to :order
  belongs_to :service
end

app/models/product.rb
class Product < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true

  def fae_display_field
    title
  end

  has_fae_image :hero_image

  belongs_to :supplier
end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  include Fae::BaseModelConcern

  enum status: { scheduled: 1, finished: 2, canceled: 3 }

  belongs_to :client
  has_many :scheduling_services
  has_many :services, through: :scheduling_services

  validates :client, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :services, presence: true

  after_save :send_email

  def fae_display_field; end

  def self.for_fae_index
    order(:date)
  end

  private

  def send_email
    SchedulingJob.perform_now(self)
  end
end

app/models/scheduling_service.rb
class SchedulingService < ApplicationRecord
  belongs_to :scheduling
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true

  def fae_display_field
    title
  end

  has_fae_image :hero_image
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include Fae::BaseModelConcern

  validates :name, presence: true
  validates :phone, presence: true
  validates :email,
            uniqueness: true,
            presence: true,
            format: {
              with: Fae.validation_helpers.email_regex,
              message: 'A valid email format is required'
            }

  def fae_display_field
    name
  end
end

app/controllers/admin/campaigns_controller.rb
module Admin
  class CampaignsController < Fae::BaseController
  end
end

app/controllers/admin/clients_controller.rb
module Admin
  class ClientsController < Fae::BaseController
  end
end

app/controllers/admin/discounts_controller.rb
module Admin
  class DiscountsController < Fae::BaseController
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Fae::BaseController
    before_action :adjust_enum, only: %i[create update]

    def adjust_enum
      params[:order][:status] = params[:order][:status].to_i
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Fae::BaseController
    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end
  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < Fae::BaseController
    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/campaigns/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :body

app/views/admin/campaigns/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = item.title
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/clients/_address_fields.html.slim
.nested-fields
  .addresses
    = f.input :name
    = link_to_remove_association 'remove address', f

app/views/admin/clients/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name
    = fae_input f, :email
    = fae_input f, :observations
    = fae_input f, :phone

    h2 Addresses
    #addresses
      = f.fields_for :addresses do |address|
        = render 'address_fields', f: address
      .links  
        = link_to_add_association 'Add Address', f, :addresses

app/views/admin/clients/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th Email
        th.-action-wide Modified
        th.-action data-sorter="false"
 
    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_client_path(item)
            td = item.email
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/discounts/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_pulldown f, :kind, collection: Discount::kinds.map { |s| s[0] }
    = fae_input f, :value, prefix: '$', placeholder: '50.00'

app/views/admin/discounts/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_discount_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/orders/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_association f, :discount
    = fae_association f, :client
    = fae_datepicker f, :date

    = fae_input f, :observations
    = fae_pulldown f, :status, size: 'long', 
                      collection: Order.statuses.to_a, 
                      selected: Order.statuses[@item.status]

    = fae_association f, :products
    = fae_association f, :services

app/views/admin/orders/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th ID
        th Date
        th Client
        th Total
        th.-action-wide Modified
        th.-action data-sorter="false"
 
    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_order_path(item)
            td = item.date
            td = item.client.name
            td = item.total
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/products/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_input f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations

    = fae_association f, :supplier

    = fae_image_form f, :hero_image

app/views/admin/products/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th Supplier
        th.-action-wide Modified
        th.-action data-sorter="false"
 
    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_product_path(item)
            td = item.price
            td = (item.supplier)? item.supplier.name : ''
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/services/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_input f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations


    = fae_image_form f, :hero_image

app/views/admin/services/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th.-action-wide Modified
        th.-action data-sorter="false"
 
    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_service_path(item)
            td = item.price
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found